spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/afrocodemy_articles?useSSL=false
    username: dummy
    password: King1234.
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      ddl-auto: create
  application:
    name: afrocodemy-articles