spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/afrocodemy_articles?useSSL=false
    username: dummy
    password: King1234.
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  application:
    name: afrocodemy-articles

server:
  port: 9000